### PR TITLE
MIDI-72: ECG training

### PR DESCRIPTION
**Pull request by SamuelJanas**
[MIDI-72](https://sacrebleu.atlassian.net/browse/MIDI-72)

I've created a config that works with ECG data, will train it later since I need the GPU for now and given it's size it's going to take a long time, feel free to edit anything here

[MIDI-72]: https://sacrebleu.atlassian.net/browse/MIDI-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by SamuelJanas** [comment]
Tagged for review just so you see the PR, not many changes to review yet

**Comment by SamuelJanas** [comment]
Wasn't able to leave the model over weekend, trained it now for 1 epoch which is 2 hours on my GPU, here's what I'm getting:
reconstructions_ecg
Not so good but I feel like all of the autoencoders need more time training, one epoch didn't do the model justice.

Trained a smaller model afterwards in half the time, during 4 epochs, these are the results:
reconstructions_ecg
A little better but I feel like more can be squeezed from changing the K value.

**Comment by roszcz** [comment]
@SamuelJanas looks like you're showing only a couple samples of noise - can you make sure to look at the results for actual ECG data, with heartbeats visible and all? :)

Also, maybe changing the plot style could help read this a bit, can you try to use a similar chart structure to what I did here:

https://github.com/Nospoko/autoencoders-demo/blob/27ce03b6eb564e04fb7c1093c7817b8d6caa020a/pipeline/autoecgcoder/evals.py#L8

image

I think it will be easier to interpret (at least for me)

**Comment by SamuelJanas** [comment]
I forgot about the noise in ECG data, you're right. Here are the results (smaller model):
ecg-vqvae-reconstruction
Re-used your code, hope it's clearer now :)
Looks pretty good to me, do you have some results from your experiments to compare? I feel like quantization works pretty good with ECG data, it's more schematic than MIDI and the bins seem to be helping

**Comment by roszcz** [comment]
I didn't get to this stage with my vq/vae-ecg experiments yet, I spent too much time generating interpolations for vae-ecg 😅 

For this, can you run some experiments with the model sizes, vq dimensionality, embedding size to get some intuition about tradeoffs in terms of accuracy and number of parameters? No need to make a detailed grid search, just a couple of educated guesses will be fine :)

**Comment by SamuelJanas** [comment]
Sure, will post the results later tonight, it might take a while to train them. I think I'll settle on ~3epochs to get the overview

**Comment by SamuelJanas** [comment]
Took longer than I expected. 
https://wandb.ai/sjanas/ECG%20VQ-VAE/runs/d8rc8jm7?workspace=user-sneakyinsect
For the experiment I run 
`python train_ecg.py --multirun model.num_embeddings=16,32,64 model.num_hiddens=64,128,256`
 (learrned that multirun exists because of that).

Kept vq dimenstionality at 100 because I was able to achieve good results with it before. I will experiment further changing just the dimenstionality on the best model. 

The best combination happened to be 64 embeddings, `medium` model size. My intuition is that the larger one would most likely get better with more training. Given the tendency to train better with larger embeddings number. I will have to look at some larger values as well, though I feel like 64 is close to optimum

reconstructions:
ecg-vqvae-reconstruction

**Comment by roszcz** [comment]
Thanks! It would also be interesting to go the other way, and find the threshold of a smallest model that still can learn anything :thinking:

**Comment by SamuelJanas** [comment]
I've trained a really small model, it had 20,470 trainable parameters.
https://wandb.ai/sjanas/ECG%20VQ-VAE/runs/385cw4vp?workspace=user-sneakyinsect
and while the test loss was growing over time, the reconstruction loss went down semi-steadily.
Here are the results I got:
ecg-vqvae-reconstruction
It's far from perfect but it learns. 
Here are the parameters important to the run 
```Python
num_embeddings: 16
num_hiddens: 16
num_residual_hiddens: 16
embedding_dim: 100
```
I'll be looking at how the num_embedings parameter impacts the learning.

**Comment by roszcz** [comment]
Interesting, to me it looks like it memorised a couple of fragments and tries to fit them to the target signal, often with very bad results :)

image

**Comment by SamuelJanas** [comment]
> Interesting, to me it looks like it memorised a couple of fragments and tries to fit them to the target signal, often with very bad results :)


I had the same thought. What's probably happening there is that the codebook is too small to represent the complexity of the data. Currently training the model with 4x bigger codebook.
https://wandb.ai/sjanas/ECG%20VQ-VAE/runs/n5i0mtyj?workspace=user-sneakyinsect
I'll post the results after ~10epochs in this comment.

ecg-vqvae-reconstruction

**Comment by roszcz** [comment]
I'm mostly interested in the failure modes for this, since it may help us understand what's going wrong with any MIDI experiments we run :)

**Comment by SamuelJanas** [comment]
> I'm mostly interested in the failure modes for this, since it may help us understand what's going wrong with any MIDI experiments we run :)

If that's the case then, from what I can see, the biggest limitting factor is the codebook size. If the codebook is too small, the model can't store enough info. On the other hand, if it's too big, it struggles to learn anything meaningful, as most of the changes happen in the "clustering" part. Model size doesn't have as big of an impact, with smaller models having higher floor for the loss value

Take a look at above comment to see how big is the impact of the `K` or `num_embeddings`.  Given that, I would start by looking at the codebook first to see if the representation isn't too sparse while debugging MIDI experiments

**Review by roszcz — APPROVED** [review]

**Pull request merged**
